-- Copied and edited from:
-- http://www.defold.com/tutorials/getting-started/
local pieces = { "go" } 

function init(self) 
    self.speed = 6
end

function update(self, dt) 
    for i, p in ipairs(pieces) do 
        local pos = go.get_position(p)
        if pos.x <= -228 then 
            pos.x = 1368 + (pos.x + 228)
        end
        pos.x = pos.x - self.speed
        go.set_position(pos, p) 
    end
end